---
server:
  port: 8761

spring:
  application:
    name:eurekaserver
  cloud:
    config:
      uri:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/